spring:
  datasource:
    url: jdbc:h2:~/local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  profiles:
    include: jwt
  h2:
    console:
      enabled: true
      path: /console

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/
    add-mappings: true


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

logging.level:
  org.hibernate.SQL: debug


